#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 01 12:42:07 CST 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim riscv_cpu_tb_behav -key {Behavioral:sim_1:Functional:riscv_cpu_tb} -tclbatch riscv_cpu_tb.tcl -view /home/thejoey/Projects/rv32i-pipelined-cpu/riscv_cpu_tb_behav.wcfg -log simulate.log"
xsim riscv_cpu_tb_behav -key {Behavioral:sim_1:Functional:riscv_cpu_tb} -tclbatch riscv_cpu_tb.tcl -view /home/thejoey/Projects/rv32i-pipelined-cpu/riscv_cpu_tb_behav.wcfg -log simulate.log

